  public void setX(int x){xCorners = x;};  
  public int getX(){return xCorners;};   
  public void setY(int y){yCorners=y;};   
  public int getY(){return yCorners;};   
  public void setDirectionX(double x){myDirectionX = x;};   
  public double getDirectionX();   
  public void setDirectionY(double y);   
  public double getDirectionY();   
  public void setPointDirection(int degrees);   
  public double getPointDirection(); 